parameters:
  svcPrincipalClientId: ''
  svcPrincipalSecret: ''
  azureTenantId: ''
  groupName: ''

stages:
- stage: Testing
  displayName: Testing

  jobs:
  - job: Execute
    steps:
    - pwsh: |

        az login --service-principal -u $env:SP_CLIENT_ID -p $env:SP_SECRET --tenant $env:AZURE_TENANT_ID
        
        $organization = "https://dev.azure.com/Aptean"
        $project = "Common Tech"
        $group = az pipelines variable-group list --org $organization --project $project --group-name $env:GROUP_NAME | ConvertFrom-Json
        if ($group.id)
        {
            Write-Host $group.variables.IMAGE_TAG.value
            $tag = $group.variables.IMAGE_TAG.value
            $friendlyNameSplit = $tag.Split("-")
            $tagVersion = $friendlyNameSplit[0]
            $friendlyName = $friendlyNameSplit[1]

            $tagVersionSplit = $tagVersion.Split(".")
            $nextPatch = [int]$tagVersionSplit[2]
            $nextPatch += 1
            $nextVersion = $tagVersionSplit[0] + "." + $tagVersionSplit[1] + "." + $nextPatch
            $nextVersion = $nextVersion + "-" + $friendlyName
            az pipelines variable-group variable update --org $organization --project $project --group-id $group.id --name "IMAGE_TAG" --value $nextVersion
        }
        Write-Host "##vso[task.setvariable variable=newTag;]$tag"
        
      displayName: Get Latest Tag
      name: GetLatestTag
      env:
          SP_CLIENT_ID: ${{ parameters.svcPrincipalClientId }}
          SP_SECRET: ${{ parameters.svcPrincipalSecret }}
          AZURE_TENANT_ID: ${{ parameters.azureTenantId }}
          GROUP_NAME: ${{ parameters.groupName }}