trigger: none

resources:
  pipelines:
  - pipeline: ezpay-payment-cancelation-retry-job-docker-build-push
    source: ezpay-payment-cancelation-retry-job-docker-build-push
    trigger:
      branches:
        include:
        - master  
  - pipeline: ezpay-account-balance-updater-job-docker-build-push
    source: ezpay-account-balance-updater-job-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: ezpay-api-svc-docker-build-push
    source: ezpay-api-svc-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: ezpay-email-notifications-docker-build-push
    source: ezpay-email-notifications-docker-build-push
    trigger:
      branches:
        include:
        - master
  # - pipeline: ezpay-erp-integration-svc-docker-build-push
  #   source: ezpay-erp-integration-svc-docker-build-push
  #   trigger:
  #     branches:
  #       include:
  #       - master
  - pipeline: ezpay-merchant-ops-svc-docker-build-push
    source: ezpay-merchant-ops-svc-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: ezpay-payfac-notifications-docker-build-push
    source: ezpay-payfac-notifications-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: ezpay-payment-ops-svc-docker-build-push
    source: ezpay-payment-ops-svc-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: ezpay-payments-svc-docker-build-push
    source: ezpay-payments-svc-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: ezpay-transaction-records-svc-docker-build-push
    source: ezpay-transaction-records-svc-docker-build-push
    trigger:
      branches:
        include:
        - master
  - pipeline: wepay-integration-svc-docker-build-push
    source: wepay-integration-svc-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: DEV_Ezpay_Helm_Deploy
  displayName: DEV - Ezpay Svcs Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-dev
    dependsOn: []

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              chartName: $(CHART_NAME)
              helmReleaseName: $(HELM_RELEASE_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              env: $(ENV)
              # Common Configs
              wepayGrpcUrl: $(WEPAY_GRPC_URL)
              wepayBaseUrl: $(WEPAY_BASE_URL)
              wepayUploadBaseUrl: $(WEPAY_UPLOAD_BASE_URL)
              merchantPortalUrl: $(MERCHANT_PORTAL_URL)
              payerPortalUrl: $(PAYER_PORTAL_URL)
              serviceBusConnString: $(SB_CONN_STRING)
              wepayApiVersion: $(WEPAY_API_VERSION)
              wepayAppId: $(WEPAY_APP_ID)
              wepayAppToken: $(WEPAY_APP_TOKEN)
              serviceBusEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              serviceBusPlatformEventsTopicConnString: $(SB_PLATFORM_EVENTS_TOPIC_CONN_STRING)
              mongoDbConnString: $(MONGODB_CONN_STRING)
              mongoDbName: $(MONGODB_DB_NAME)
              mongoDbPaymentCancelRetriesCollectionName: $(MONGODB_PAYMENT_CANCEL_RETRIES_COLLECTION)
              mongoDbIdempotencyCollectionName: $(MONGODB_IDEMPOTENCY_COLLECTION)
              mongoDbEzpayApiSvcCollectionName: $(MONGODB_EZPAY_API_SVC_COLLECTION)
              mongoDbEmailNotificationSvcCollectionName: $(MONGODB_EMAIL_NOTIFICATIONS_SVC_COLLECTION)
              mongoDbPaymentsSvcCollectionName: $(MONGODB_PAYMENTS_SVC_COLLECTION)
              mongoDbTxnRecordsSvcCollectionName: $(MONGODB_TXN_RECORDS_SVC_COLLECTION)              
              frontDoorId: $(FRONT_DOOR_ID)
              sentryDsn: $(SENTRY_DSN)
              # Cancel Payment Retry Job
              paymentCancelRetryJobImageRepositoryName: $(PAYMENT_CANCEL_RETRY_JOB_IMAGE_REPOSITORY_NAME)
              paymentCancelRetryJobConfigCronSchedule: $(PAYMENT_CANCEL_RETRY_JOB_CRON_SCHEDULE)
              paymentCancelRetryJobConfigSuccessfulJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_SUCCESSFUL_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobConfigFailedJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_FAILED_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobNodeSelectorPool: $(PAYMENT_CANCEL_RETRY_JOB_NODE_SELECTOR_POOL)
              # ACCOUNT BALANCE UPDATE JOB
              acctBalanceJobImageRepositoryName: $(ACCT_BALANCE_JOB_IMAGE_REPOSITORY_NAME)
              acctBalanceJobSuccessfulJobHistoryLimit: $(ACCT_BALANCE_JOB_SUCCESSFUL_JOB_HISTORY_LIMIT)
              acctBalanceJobFailedJobHistoryLimit: $(ACCT_BALANCE_JOB_FAILED_JOB_HISTORY_LIMIT)
              acctBalanceJobCronSchedule: $(ACCT_BALANCE_JOB_CRON_SCHEDULE)
              acctBalanceJobNodeSelectorPool: $(ACCT_BALANCE_JOB_NODE_SELECTOR_POOL)  
              # EZPAY API SVC         
              ezpayApiSvcImageRepositoryName: $(EZPAY_API_SVC_IMAGE_REPOSITORY_NAME)
              ezpayApiSvcReplicas: $(EZPAY_API_SVC_REPLICAS)
              ezpayApiSvcNodeSelectorPool: $(EZPAY_API_SVC_NODE_SELECTOR_POOL)
              ezpayApiSvcResourceLimitsCpu: $(EZPAY_API_SVC_RESOURCE_LIMITS_CPU)
              ezpayApiSvcResourceLimitsMemory: $(EZPAY_API_SVC_RESOURCE_LIMITS_MEMORY)
              ezpayApiSvcResourceRequestsCpu: $(EZPAY_API_SVC_RESOURCE_REQUESTS_CPU)
              ezpayApiSvcResourceRequestsMemory: $(EZPAY_API_SVC_RESOURCE_REQUESTS_MEMORY)
              ezpayApiSvcKongIngressUpstreamHostHeader: $(EZPAY_API_SVC_KONG_INGRESS_UPSTREAM_HEADER)
              ezpayApiSvcKongIngressClass: $(EZPAY_API_SVC_KONG_INGRESS_CLASS)
              ezpayApiSvcCosdbConnString: $(EZPAY_API_SVC_COSMOSDB_CONN_STRING)
              ezpayApiSvcCosdbDatabase: $(EZPAY_API_SVC_COSMOSDB_DATABASE)
              ezpayApiSvcCosdbContainer: $(EZPAY_API_SVC_COSMOSDB_CONTAINER)
              ezpayApiSvcSbPlatformEventsSubscription: $(EZPAY_API_SVC_SB_PLATFORM_EVENTS_SUBSCRIPTION)
              ezpayApiSvcAppInsightsKey: $(EZPAY_API_SVC_APP_INSIGHTS_INSTRUMENTATION_KEY)
              ezpayApiSvcB2cClientId: $(EZPAY_API_SVC_B2C_CLIENT_ID)
              ezpayApiSvcB2cDomainHost: $(EZPAY_API_SVC_B2C_DOMAIN_HOST)
              ezpayApiSvcB2cTenantId: $(EZPAY_API_SVC_B2C_TENANT_ID)
              ezpayApiSvcB2cPolicyName: $(EZPAY_API_SVC_B2C_POLICY_NAME)
              ezpayApiSvcSubsMgmtGrpcUrl: $(SUBS_MGMT_GRPC_URL)
              ezpayApiSvcSubsMgmtApiKey: $(EZPAY_API_SVC_SUBS_MGMT_API_KEY)
              ezpayApiSvcSubsMgmtServiceId: $(EZPAY_API_SVC_SUBS_MGMT_SERVICE_ID)
              ezpayApiSvcPaymentPlatformFromPhoneNumber: $(PAYMENTS_PLATFORM_FROM_PHONE_NUMBER)
              ezpayApiSvcPaymentPlatformFromEmail: $(EZPAY_API_SVC_PAYMENTS_PLATFORM_FROM_EMAIL)
              ezpayApiSvcProcessPlatformEvents: $(EZPAY_API_SVC_PROCESS_PLATFORM_EVENTS)
              ezpayApiSvcBlobStorageUrl: $(EZPAY_API_SVC_BLOB_STORAGE_URL)
              ezpayApiSvcEncryptPayerUrlToken: $(EZPAY_API_SVC_ENCRYPT_PAYER_URL_TOKEN)
              ezpayApiSvcEncryptKey: $(EZPAY_API_SVC_ENCRYPTION_KEY)
              ezpayApiSvcTosVersion: $(EZPAY_API_SVC_TOS_VERSION)
              ezpayApiSvcStatementsContainerName: $(EZPAY_API_SVC_STATEMENTS_CONTAINER_NAME)
              ezpayApiSvcInvoiceContainerName: $(EZPAY_API_SVC_INVOICE_CONTAINER_NAME)
              ezpayApiSvcInvoiceBlobConnString: $(EZPAY_API_SVC_INVOICE_BLOB_CONNECTION_STRING)
              ezpayApiSvcLogicAppUrlShortenerUrl: $(EZPAY_API_SVC_LOGIC_APP_URL_SHORTENER_URL)
              ezpayApiSvcProductApisOnly: $(EZPAY_API_SVC_PRODUCT_APIS_ONLY)
              #ezpayApiSvcNodeJsEnv: $(EZPAY_API_SVC_)  
              # EMAIL NOTIFICATION SVC
              emailNotificationSvcImageRepositoryName: $(EMAIL_NOTIFICATION_SVC_IMAGE_REPOSITORY_NAME)
              emailNotificationSvcReplicas: $(EMAIL_NOTIFICATION_SVC_REPLICAS)
              emailNotificationSvcNodeSelectorPool: $(EMAIL_NOTIFICATION_SVC_NODE_SELECTOR_POOL)
              emailNotificationSvcResourceLimitsCpu: $(EMAIL_NOTIFICATION_SVC_RESOURCE_LIMITS_CPU)
              emailNotificationSvcResourceLimitsMemory: $(EMAIL_NOTIFICATION_SVC_RESOURCE_LIMITS_MEMORY)
              emailNotificationSvcResourceRequestsCpu: $(EMAIL_NOTIFICATION_SVC_RESOURCE_REQUESTS_CPU)
              emailNotificationSvcResourceRequestsMemory: $(EMAIL_NOTIFICATION_SVC_RESOURCE_REQUESTS_MEMORY)
              emailNotificationSvcDbPlatformEventsSubscription: $(EMAIL_NOTIFICATION_SVC_SB_PLATFORM_EVENTS_SUBSCRIPTION)
              emailNotificationSvcAppInsightsKey: $(EMAIL_NOTIFICATION_SVC_APP_INSIGHTS_INSTRUMENTATION_KEY)
              emailNotificationSvcBroadcastPlatformEvents: $(EMAIL_NOTIFICATION_SVC_BROADCAST_PLATFORM_EVENTS)
              emailNotificationSvcEmailTemplateLogoUrl: $(EMAIL_NOTIFICATION_SVC_EMAIL_TEMPLATE_LOGO_URL)
              emailNotificationSvcPlatformEmail: $(EMAIL_NOTIFICATION_SVC_PLATFORM_EMAIL)
              emailNotificationSvcPlatformName: $(EMAIL_NOTIFICATION_SVC_PLATFORM_NAME)
              emailNotificationSvcProcessPlatformEvents: $(EMAIL_NOTIFICATION_SVC_PROCESS_PLATFORM_EVENTS)
              # ERP INTEGRATION SVC
              erpIntegrationSvcImageRepositoryName: $(ERP_INTEGRATION_SVC_IMAGE_REPOSITORY_NAME)
              erpIntegrationSvcReplicas: $(ERP_INTEGRATION_SVC_REPLICAS)
              erpIntegrationSvcNodeSelectorPool: $(ERP_INTEGRATION_SVC_NODE_SELECTOR_POOL)
              erpIntegrationSvcResourceLimitsCpu: $(ERP_INTEGRATION_SVC_RESOURCE_LIMITS_CPU)
              erpIntegrationSvcResourceLimitsMemory: $(ERP_INTEGRATION_SVC_RESOURCE_LIMITS_MEMORY)
              erpIntegrationSvcResourceRequestsCpu: $(ERP_INTEGRATION_SVC_RESOURCE_REQUESTS_CPU)
              erpIntegrationSvcResourceRequestsMemory: $(ERP_INTEGRATION_SVC_RESOURCE_REQUESTS_MEMORY)
              erpIntegrationSvcKongIngressUpstreamHostHeader: $(ERP_INTEGRATION_SVC_KONG_INGRESS_UPSTREAM_HEADER)
              erpIntegrationSvcKongIngressClass: $(ERP_INTEGRATION_SVC_KONG_INGRESS_CLASS)
              erpIntegrationSvcEzpayApiSvcGqlUrl: $(ERP_INTEGRATION_SVC_GQL_URL_EZPAY_API_SVC)
              erpIntegrationSvcSyncTimeout: $(ERP_INTEGRATION_SVC_SYNC_TIMEOUT)
              erpIntegrationSvcSyncMaxWaitTime: $(ERP_INTEGRATION_SVC_SYNC_MAX_WAIT_TIME)
              # MERCHANT OPS SVC
              merchantOpsSvcImageRepositoryName: $(MERCHANT_OPS_SVC_IMAGE_REPOSITORY_NAME)
              merchantOpsSvcReplicas: $(MERCHANT_OPS_SVC_REPLICAS)
              merchantOpsSvcNodeSelectorPool: $(MERCHANT_OPS_SVC_NODE_SELECTOR_POOL)
              merchantOpsSvcResourceLimitsCpu: $(MERCHANT_OPS_SVC_RESOURCE_LIMITS_CPU)
              merchantOpsSvcResourceLimitsMemory: $(MERCHANT_OPS_SVC_RESOURCE_LIMITS_MEMORY)
              merchantOpsSvcResourceRequestsCpu: $(MERCHANT_OPS_SVC_RESOURCE_REQUESTS_CPU)
              merchantOpsSvcResourceRequestsMemory: $(MERCHANT_OPS_SVC_RESOURCE_REQUESTS_MEMORY)
              merchantOpsSvcPlatformEventsSubscription: $(MERCHANT_OPS_SVC_SB_PLATFORM_EVENTS_SUBSCRIPTION)
              merchantOpsSvcEnableAppInsights: $(MERCHANT_OPS_SVC_ENABLE_APP_INSIGHTS)
              merchantOpsSvcEnableK8sAppInsights: $(MERCHANT_OPS_SVC_ENABLE_K8S_APP_INSIGHTS)
              # PAYFAC NOTIFICATIONS SVC
              payfacNotificationsSvcImageRepositoryName: $(PAYFAC_NOTIFICATIONS_SVC_IMAGE_REPOSITORY_NAME)
              payfacNotificationsSvcReplicas: $(PAYFAC_NOTIFICATIONS_SVC_REPLICAS)
              payfacNotificationsSvcNodeSelectorPool: $(PAYFAC_NOTIFICATIONS_SVC_NODE_SELECTOR_POOL)
              payfacNotificationsSvcResourceLimitsCpu: $(PAYFAC_NOTIFICATIONS_SVC_RESOURCE_LIMITS_CPU)
              payfacNotificationsSvcResourceLimitsMemory: $(PAYFAC_NOTIFICATIONS_SVC_RESOURCE_LIMITS_MEMORY)
              payfacNotificationsSvcResourceRequestCpu: $(PAYFAC_NOTIFICATIONS_SVC_RESOURCE_REQUESTS_CPU)
              payfacNotificationsSvcResourceRequestMemory: $(PAYFAC_NOTIFICATIONS_SVC_RESOURCE_REQUESTS_MEMORY)
              payfacNotificationsSvcSbPayfacTopicConnString: $(PAYFAC_NOTIFICATIONS_SVC_SB_PAYFAC_NOTIFICATIONS_TOPIC_CONN_STRING)
              payfacNotificationsSvcSbPayfacSubscription: $(PAYFAC_NOTIFICATIONS_SVC_SB_PAYFAC_NOTIFICATIONS_SUBSCRIPTION)
              payfacNotificationsSvcSbPayfacTopic: $(PAYFAC_NOTIFICATIONS_SVC_SB_PAYFAC_NOTIFICATIONS_TOPIC)
              payfacNotificationsSvcAppInsightsKey: $(PAYFAC_NOTIFICATIONS_SVC_APP_INSIGHTS_INSTRUMENTATION_KEY)
              payfacNotificationsSvcEzpayWebhookUrl: $(PAYFAC_NOTIFICATIONS_SVC_EZPAY_WEBHOOK_URL)
              payfacNotificationsSvcProcessPlatformEvents: $(PAYFAC_NOTIFICATIONS_SVC_PROCESS_PLATFORM_EVENTS)
              payfacNotificationsSvcProcessNotificationEvents: $(PAYFAC_NOTIFICATIONS_SVC_PROCESS_NOTIFICATION_EVENTS)
              payfacNotificationsSvcBroadcastPlatformEvents: $(PAYFAC_NOTIFICATIONS_SVC_BROADCAST_PLATFORM_EVENTS)
              # PAYMENT OPS SVC
              paymentOpsSvcImageRepositoryName: $(PAYMENT_OPS_SVC_IMAGE_REPOSITORY_NAME)
              paymentOpsSvcReplicas: $(PAYMENT_OPS_SVC_REPLICAS)
              paymentOpsSvcNodeSelectorPool: $(PAYMENT_OPS_SVC_NODE_SELECTOR_POOL)
              paymentOpsSvcResourceLimitsCpu: $(PAYMENT_OPS_SVC_RESOURCE_LIMITS_CPU)
              paymentOpsSvcResourceLimitsMemory: $(PAYMENT_OPS_SVC_RESOURCE_LIMITS_MEMORY)
              paymentOpsSvcResourceRequestsCpu: $(PAYMENT_OPS_SVC_RESOURCE_REQUESTS_CPU)
              paymentOpsSvcResourceRequestsMemory: $(PAYMENT_OPS_SVC_RESOURCE_REQUESTS_MEMORY)
              paymentOpsSvcSbPlatformEventsSubscription: $(PAYMENT_OPS_SVC_SB_PLATFORM_EVENTS_SUBSCRIPTION)
              paymentOpsSvcSbEmailReqQueueConnString: $(PAYMENT_OPS_SVC_SB_EMAIL_REQS_QUEUE_CONN_STRING)
              paymentOpsSvcSbEmailReqQueue: $(PAYMENT_OPS_SVC_SB_EMAIL_REQS_QUEUE)
              paymentOpsSvcSbSmsReqQueueConnString: $(PAYMENT_OPS_SVC_SB_SMS_REQS_QUEUE_CONN_STRING)
              paymentOpsSvcSbSmsReqQueue: $(PAYMENT_OPS_SVC_SB_SMS_REQS_QUEUE)
              paymentOpsSvcEnableAppInsights: $(PAYMENT_OPS_SVC_ENABLE_APP_INSIGHTS)
              paymentOpsSvcEnableK8sAppInsights: $(PAYMENT_OPS_SVC_ENABLE_K8S_APP_INSIGHTS)  
              # PAYMENTS SVC & PAYMENTS RETRY JOB
              paymentsSvcImageRepositoryName: $(PAYMENTS_SVC_IMAGE_REPOSITORY_NAME)
              paymentsSvcReplicas: $(PAYMENTS_SVC_REPLICAS)
              paymentsSvcNodeSelectorPool: $(PAYMENTS_SVC_NODE_SELECTOR_POOL)
              paymentsSvcResourceLimitsCpu: $(PAYMENTS_SVC_RESOURCE_LIMITS_CPU)
              paymentsSvcResourceLimitsMemory: $(PAYMENTS_SVC_RESOURCE_LIMITS_MEMORY)
              paymentsSvcResourceRequestsCpu: $(PAYMENTS_SVC_RESOURCE_REQUESTS_CPU)
              paymentsSvcResourceRequestsMemory: $(PAYMENTS_SVC_RESOURCE_REQUESTS_MEMORY)
              paymentsSvcPlatformEventsSubscription: $(PAYMENTS_SVC_SB_PLATFORM_EVENTS_SUBSCRIPTION)
              paymentsSvcCronSchedule: $(PAYMENTS_SVC_CRON_SCHEDULE)
              paymentsSvcSuccessfulJobHistoryLimit: $(PAYMENTS_SVC_SUCCESSFUL_JOB_HISTORY_LIMIT)
              paymentsSvcFailedJobHistoryLimit: $(PAYMENTS_SVC_FAILED_JOB_HISTORY_LIMIT)
              paymentsSvcEnableAppInsights: $(PAYMENTS_SVC_ENABLE_APP_INSIGHTS)
              paymentsSvcEnableK8sAppInsights: $(PAYMENTS_SVC_ENABLE_K8S_APP_INSIGHTS)  
              # TRANSACTION RECORDS SVC & TRANSACTION RECORDS RETRIEVE JOB & TRANSACTION RECORDS STATEMENT JOB               
              txnRecordsSvcImageRepositoryName: $(TXN_RECORDS_SVC_IMAGE_REPOSITORY_NAME)
              txnRecordsSvcReplicas: $(TXN_RECORDS_SVC_REPLICAS)
              txnRecordsSvcNodeSelectorPool: $(TXN_RECORDS_SVC_NODE_SELECTOR_POOL)
              txnRecordsSvcResourceLimitCpu: $(TXN_RECORDS_SVC_RESOURCE_LIMITS_CPU)
              txnRecordsSvcResourceLimitMemory: $(TXN_RECORDS_SVC_RESOURCE_LIMITS_MEMORY)
              txnRecordsSvcResourceRequestCpu: $(TXN_RECORDS_SVC_RESOURCE_REQUESTS_CPU)
              txnRecordsSvcResourceRequestMemory: $(TXN_RECORDS_SVC_RESOURCE_REQUESTS_MEMORY)
              txnRecordsStmtsResourceLimitCpu: $(TXN_RECORDS_STMTS_RESOURCE_LIMITS_CPU)
              txnRecordsStmtsResourceLimitMemory: $(TXN_RECORDS_STMTS_RESOURCE_LIMITS_MEMORY)
              txnRecordsStmtsResourceRequestCpu: $(TXN_RECORDS_STMTS_RESOURCE_REQUESTS_CPU)
              txnRecordsStmtsResourceRequestMemory: $(TXN_RECORDS_STMTS_RESOURCE_REQUESTS_MEMORY)              
              txnRecordsSvcBroadcastPlatformEvents: $(TXN_RECORDS_SVC_BROADCAST_PLATFORM_EVENTS)
              txnRecordsSvcPlatformEmail: $(TXN_RECORDS_SVC_PLATFORM_EMAIL)
              txnRecordsSvcDbPlatformEventsSubscription: $(TXN_RECORDS_SVC_SB_PLATFORM_EVENTS_SUBSCRIPTION)
              txnRecordsSvcAppInsightsKey: $(TXN_RECORDS_SVC_APP_INSIGHTS_INSTRUMENTATION_KEY)
              txnRecordsSvcProcessPlatformEvents: $(TXN_RECORDS_SVC_PROCESS_PLATFORM_EVENTS)
              txnRecordsSvcStatementsContainer: $(TXN_RECORDS_SVC_STATEMENTS_CONTAINER_NAME)
              txnRecordsSvcStatementPeriod: $(TXN_RECORDS_SVC_STATEMENT_PERIOD)
              txnRecordsSvcStatementsBlobConnString: $(TXN_RECORDS_SVC_STATEMENTS_BLOB_CONNECTION_STRING)
              txnRecordsSvcGeneratePdfStatement: $(TXN_RECORDS_SVC_GENERATE_PDF_STATEMENT)
              txnRecordsSvcGenerateStatementChunkSize: $(TXN_RECORDS_SVC_GENERATE_STATEMENT_CHUNK_SIZE)
              txnRecordsSvcCronSchedule: $(TXN_RECORDS_SVC_CRON_SCHEDULE)
              txnRecordsSvcSuccessfulJobHistoryLimit: $(TXN_RECORDS_SVC_SUCCESSFUL_JOB_HISTORY_LIMIT)
              txnRecordsSvcFailedJobHistoryLimit: $(TXN_RECORDS_SVC_FAILED_JOB_HISTORY_LIMIT)
              # WEPAY INTEGRATION SVC
              wepayIntegrationSvcImageRepositoryName: $(WEPAY_INTEGRATION_SVC_IMAGE_REPOSITORY_NAME)
              wepayIntegrationSvcReplicas: $(WEPAY_INTEGRATION_SVC_REPLICAS)
              wepayIntegrationSvcNodeSelectorPool: $(WEPAY_INTEGRATION_SVC_NODE_SELECTOR_POOL)
              wepayIntegrationSvcResourceLimitsCpu: $(WEPAY_INTEGRATION_SVC_RESOURCE_LIMITS_CPU)
              wepayIntegrationSvcResourceLimitsMemory: $(WEPAY_INTEGRATION_SVC_RESOURCE_LIMITS_MEMORY)
              wepayIntegrationSvcResourceRequestCpu: $(WEPAY_INTEGRATION_SVC_RESOURCE_REQUESTS_CPU)
              wepayIntegrationSvcResourceRequestMemory: $(WEPAY_INTEGRATION_SVC_RESOURCE_REQUESTS_MEMORY)                            