trigger: none

resources:
  pipelines:
  - pipeline: k6-docker-build-push
    source: k6-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: PRF_k6_Helm_Deploy
  displayName: PRF - k6 scripts Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: k6-prf
    dependsOn: []

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: k6-prf
    - template: helm-variables-prf.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              chartName: $(CHART_NAME)
              helmReleaseName: $(HELM_RELEASE_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              env: $(ENV)
              # k6
              k6ScriptsImageTag: $(K6_SCRIPTS_IMAGE_TAG)
              k6ScriptsImageRepositoryName: $(K6_SCRIPTS_IMAGE_REPOSITORY_NAME)
              k6ScriptsNodeSelectorPool: $(K6_SCRIPTS_NODE_SELECTOR_POOL)
              k6ScriptsResourceLimitsCpu: $(K6_SCRIPTS_RESOURCE_LIMITS_CPU)
              k6ScriptsResourceLimitsMemory: $(K6_SCRIPTS_RESOURCE_LIMITS_MEMORY)
              k6ScriptsResourceRequestsCpu: $(K6_SCRIPTS_RESOURCE_REQUESTS_CPU)
              k6ScriptsResourceRequestsMemory: $(K6_SCRIPTS_RESOURCE_REQUESTS_MEMORY)
              k6StatsDServiceAddress: $(K6_STATSD_ADDR)
              # crm
              crmLoadTenantId: $(CRM_LOAD_CRM_TENANT_ID)
              crmLoadTenantSecret: $(CRM_LOAD_CRM_TENANT_SECRET)
              crmLoadApiKey: $(CRM_LOAD_CRM_API_KEY)
