trigger: none

resources:
  pipelines:
  - pipeline: integration-communication-hub-docker-build-push
    source: integration-communication-hub-docker-build-push
    trigger:
      branches:
        include:
        - main

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: Atg_Comm_Hub_Dev_Deploy
  displayName: ATG Comm Hub Dev Deploy

  jobs:
  - deployment: App_Service_Deploy
    displayName: App Service Deploy
    environment: atg-commhub-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: atg-commhub-dev
    - name: latestTag
      value: ''

    strategy:
      runOnce:
        deploy:
          steps:
          - template: app-svc-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: '560ec2b0-df0c-4e8c-9848-a15718863bb6'
              appServiceName: 'apsvc-westus2-dev-integration-commhub'
              containerRegistryName: 'acreastusshrapteancr.azurecr.io'
              imageRepositoryName: 'integration-communication-hub'
              appInsightsInstrumentationKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              appInsightsConnString: $(APP_INSIGHTS_CONN_STRING)
              gqlUrlSubsMgmt: $(GQL_URL_SUBS_MGMT)
              sbConnString: $(SB_CONN_STRING)
              sbResultSubscriptionName: $(SB_RESULT_SUBSCRIPTION_NAME)
              sbSubscriptionName: $(SB_SUBSCRIPTION_NAME)
              sbTopicName: $(SB_TOPIC_NAME)
              signalRConnString: $(SIGNALR_CONN_STRING)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              subsMgmtTenantSecret: $(SUBS_MGMT_TENANT_SECRET)              


