variables:
- group: docker-acr-principal-config

stages:
- stage: Build
  displayName: Fetch latest from shared ACR, retag and push to prod ACR.

  jobs:
  - job: Execute

    pool:
      vmImage: ubuntu-latest

    steps:
    - pwsh: |
        az login --service-principal -u $(SERVICE_PRINCIPAL_CLIENT_ID_SHR) -p $(SERVICE_PRINCIPAL_SECRET_SHR) --tenant $(tenantId)
        $fullRegistryName = "$(ACR_FULL_NAME_SHR)"
        $latestTag = az acr repository show-tags --name $(ACR_SHORT_NAME_SHR) --repository comms-api-svc --top 1 --orderby time_desc | ConvertFrom-Json
        az logout    
        docker login $(ACR_FULL_NAME_SHR) -u $(ACR_SHORT_NAME_SHR) -p $(ACR_USER_PASSWORD_SECRET_SHR)
        docker pull $(ACR_FULL_NAME_SHR)/comms-api-svc:$latestTag
        docker tag $(ACR_FULL_NAME_SHR)/comms-api-svc:$latestTag $(ACR_FULL_NAME_PRD)/comms-api-svc:$latestTag
        docker login $(ACR_FULL_NAME_PRD) -u $(ACR_SHORT_NAME_PRD) -p $(ACR_USER_PASSWORD_SECRET_SHR)
        docker push $(ACR_FULL_NAME_PRD)/comms-api-svc:$latestTag      
      displayName: Copy Docker Images
      name: copyImages

    