variables:
- group: docker-acr-principal-config

stages:
- stage: Build
  displayName: Fetch latest from shared ACR, retag and push to prod ACR.

  jobs:
  - job: Copy Docker Images

    pool:
      vmImage: ubuntu-latest

    steps:
      - template: templates\docker-copy-image-to-prod.yaml
        parameters:
          serviceName: comms-api-svc

      - template: templates\docker-copy-image-to-prod.yaml
        parameters:
          serviceName: subs-mgmt-api-svc