
parameters:
  variableGroup: ''
  dropArtifactPath: ''
  targetEnvironment: ''
  azureServiceConnection: ''

jobs:
- deployment: Deploy_Website
  displayName: Deploy Website
  environment: ${{ parameters.targetEnvironment }}

  pool:
    vmImage: 'ubuntu-latest'

  variables:
  - group: ${{ parameters.variableGroup }}

  strategy:
    runOnce:
      deploy:
        steps:
        - task: ExtractFiles@1
          displayName: Extract assets from zip
          inputs:
            archiveFilePatterns: ${{ parameters.dropArtifactPath }}
            destinationFolder: $(System.DefaultWorkingDirectory)/static
            cleanDestinationFolder: true

        - task: AzureCLI@2
          displayName: Push to storage account fileshare
          inputs:
            azureSubscription: ${{ parameters.azureServiceConnection }}
            scriptType: 'pscore'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az storage file upload-batch --account-name "$(STATIC_WEB_FILES_AZ_STORAGE_ACCT_NAME)" --account-key "$(STATIC_WEB_FILES_AZ_STORAGE_ACCT_KEY)" --connection-string "$(STATIC_WEB_FILES_AZ_STORAGE_ACCT_CONN_STRING)" --source ./ --destination webfiles --destination-path $(STATIC_WEB_FILES_DESTINATION_PATH)
            workingDirectory: '$(System.DefaultWorkingDirectory)/static'