trigger: none

resources:
  pipelines:
  - pipeline: ezpay-payfac-notifications-docker-build-push
    source: ezpay-payfac-notifications-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: DEV_Payfac_Notifications_Svc_Helm_Deploy
  displayName: DEV - Ezpay Payfac Notifications SVC Helm Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-payfac-notifications-svc-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              wepayBaseUrl: $(WEPAY_BASE_URL)
              wepayApiVersion: $(WEPAY_API_VERSION)
              wepayAppId: $(WEPAY_APP_ID)
              wepayAppToken: $(WEPAY_APP_TOKEN)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              ezpayWebHookUrl: $(EZPAY_WEBHOOK_URL)
              eventTopicConnectionString: $(SB_PLATFORM_EVENTS_TOPIC_CONN_STRING)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              processNotificationEvents: $(PROCESS_NOTIFICATION_EVENTS)
              serviceBusConnectionString: $(SB_CONN_STRING)   
              payfacTopicConnectionString: $(SB_PAYFAC_NOTIFICATIONS_TOPIC_CONN_STRING)
              platformEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              payfacNotificationTopic: $(SB_PAYFAC_NOTIFICATIONS_TOPIC)
              payfacNotificationSubscription: $(SB_PAYFAC_NOTIFICATIONS_SUBSCRIPTION)

- stage: TST_Payfac_Notifications_Svc_Helm_Deploy
  displayName: TST - Ezpay Payfac Notifications SVC Helm Deploy
  dependsOn: DEV_Payfac_Notifications_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-tst

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-payfac-notifications-svc-tst
    - template: helm-variables-tst.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              wepayBaseUrl: $(WEPAY_BASE_URL)
              wepayApiVersion: $(WEPAY_API_VERSION)
              wepayAppId: $(WEPAY_APP_ID)
              wepayAppToken: $(WEPAY_APP_TOKEN)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              ezpayWebHookUrl: $(EZPAY_WEBHOOK_URL)
              eventTopicConnectionString: $(SB_PLATFORM_EVENTS_TOPIC_CONN_STRING)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              processNotificationEvents: $(PROCESS_NOTIFICATION_EVENTS)
              serviceBusConnectionString: $(SB_CONN_STRING)   
              payfacTopicConnectionString: $(SB_PAYFAC_NOTIFICATIONS_TOPIC_CONN_STRING)
              platformEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              payfacNotificationTopic: $(SB_PAYFAC_NOTIFICATIONS_TOPIC)
              payfacNotificationSubscription: $(SB_PAYFAC_NOTIFICATIONS_SUBSCRIPTION)         

- stage: STG_Payfac_Notifications_Svc_Helm_Deploy
  displayName: STG - Ezpay Payfac Notifications SVC Helm Deploy
  dependsOn: TST_Payfac_Notifications_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-stg

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-payfac-notifications-svc-stg
    - template: helm-variables-stg.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              wepayBaseUrl: $(WEPAY_BASE_URL)
              wepayApiVersion: $(WEPAY_API_VERSION)
              wepayAppId: $(WEPAY_APP_ID)
              wepayAppToken: $(WEPAY_APP_TOKEN)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              ezpayWebHookUrl: $(EZPAY_WEBHOOK_URL)
              eventTopicConnectionString: $(SB_PLATFORM_EVENTS_TOPIC_CONN_STRING)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              processNotificationEvents: $(PROCESS_NOTIFICATION_EVENTS)
              serviceBusConnectionString: $(SB_CONN_STRING)   
              payfacTopicConnectionString: $(SB_PAYFAC_NOTIFICATIONS_TOPIC_CONN_STRING)
              platformEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              payfacNotificationTopic: $(SB_PAYFAC_NOTIFICATIONS_TOPIC)
              payfacNotificationSubscription: $(SB_PAYFAC_NOTIFICATIONS_SUBSCRIPTION)                   

- stage: PRD_Payfac_Notifications_Svc_Helm_Deploy
  displayName: PRD - Ezpay Payfac Notifications SVC Helm Deploy
  dependsOn: STG_Payfac_Notifications_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-prd

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-payfac-notifications-svc-prd
    - template: helm-variables-prd.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-PRD'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              wepayBaseUrl: $(WEPAY_BASE_URL)
              wepayApiVersion: $(WEPAY_API_VERSION)
              wepayAppId: $(WEPAY_APP_ID)
              wepayAppToken: $(WEPAY_APP_TOKEN)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              ezpayWebHookUrl: $(EZPAY_WEBHOOK_URL)
              eventTopicConnectionString: $(SB_PLATFORM_EVENTS_TOPIC_CONN_STRING)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              processNotificationEvents: $(PROCESS_NOTIFICATION_EVENTS)
              serviceBusConnectionString: $(SB_CONN_STRING)   
              payfacTopicConnectionString: $(SB_PAYFAC_NOTIFICATIONS_TOPIC_CONN_STRING)
              platformEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              payfacNotificationTopic: $(SB_PAYFAC_NOTIFICATIONS_TOPIC)
              payfacNotificationSubscription: $(SB_PAYFAC_NOTIFICATIONS_SUBSCRIPTION)            