trigger: none

resources:
  pipelines:
  - pipeline: ezpay-api-svc-docker-build-push
    source: ezpay-api-svc-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: DEV_API_Svc_Helm_Deploy
  displayName: DEV - Ezpay API SVC Helm Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-api-svc-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-api-svc-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)

- stage: TST_API_Svc_Helm_Deploy
  displayName: TST - Ezpay API SVC Helm Deploy
  dependsOn: DEV_API_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-api-svc-tst

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-api-svc-tst
    - template: helm-variables-tst.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)

- stage: STG_API_Svc_Helm_Deploy
  displayName: STG - Ezpay API SVC Helm Deploy
  dependsOn: TST_API_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-api-svc-stg

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-api-svc-stg
    - template: helm-variables-stg.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)

- stage: PRD_API_Svc_Helm_Deploy
  displayName: PRD - Ezpay API SVC Helm Deploy
  dependsOn: STG_API_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-api-svc-prd

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-api-svc-prd
    - template: helm-variables-prd.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-PRD'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_PRD)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_PRD)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
