trigger: none

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: TST_Ezpay_Helm_Deploy
  displayName: TST - Ezpay Svcs Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-tst
    dependsOn: []

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-tst
    - template: ../ezpay-svcs/helm-variables-tst.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../ezpay-svcs/helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              chartName: $(CHART_NAME)
              helmReleaseName: $(HELM_RELEASE_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              env: $(ENV)
              # Common Configs
              wepayGrpcUrl: $(WEPAY_GRPC_URL)
              # Cancel Payment Retry Job
              paymentCancelRetryJobImageRepositoryName: $(PAYMENT_CANCEL_RETRY_JOB_IMAGE_REPOSITORY_NAME)
              paymentCancelRetryJobConfigMongoDbConnString: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_CONN_STRING)
              paymentCancelRetryJobConfigMongoDbDatabase: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_DATABASE)
              paymentCancelRetryJobConfigMongoDbCollectionName: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_COLLECTION_NAME)
              paymentCancelRetryJobConfigCronSchedule: $(PAYMENT_CANCEL_RETRY_JOB_CRON_SCHEDULE)
              paymentCancelRetryJobConfigSuccessfulJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_SUCCESSFUL_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobConfigFailedJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_FAILED_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobNodeSelectorPool: $(PAYMENT_CANCEL_RETRY_JOB_NODE_SELECTOR_POOL)

- stage: STG_Ezpay_Helm_Deploy
  displayName: STG - Ezpay Svcs Helm Deploy
  dependsOn: TST_Ezpay_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-stg
    dependsOn: []

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-stg
    - template: ../ezpay-svcs/helm-variables-stg.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../ezpay-svcs/helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              chartName: $(CHART_NAME)
              helmReleaseName: $(HELM_RELEASE_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              env: $(ENV)
              # Common Configs
              wepayGrpcUrl: $(WEPAY_GRPC_URL)
              # Cancel Payment Retry Job
              paymentCancelRetryJobImageRepositoryName: $(PAYMENT_CANCEL_RETRY_JOB_IMAGE_REPOSITORY_NAME)
              paymentCancelRetryJobConfigMongoDbConnString: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_CONN_STRING)
              paymentCancelRetryJobConfigMongoDbDatabase: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_DATABASE)
              paymentCancelRetryJobConfigMongoDbCollectionName: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_COLLECTION_NAME)
              paymentCancelRetryJobConfigCronSchedule: $(PAYMENT_CANCEL_RETRY_JOB_CRON_SCHEDULE)
              paymentCancelRetryJobConfigSuccessfulJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_SUCCESSFUL_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobConfigFailedJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_FAILED_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobNodeSelectorPool: $(PAYMENT_CANCEL_RETRY_JOB_NODE_SELECTOR_POOL)

- stage: PRD_Ezpay_Helm_Deploy
  displayName: PRD - Ezpay Svcs Helm Deploy
  dependsOn: STG_Ezpay_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-prd
    dependsOn: []

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-prd
    - template: ../ezpay-svcs/helm-variables-prd.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../ezpay-svcs/helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-PRD'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_PRD)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_PRD)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              chartName: $(CHART_NAME)
              helmReleaseName: $(HELM_RELEASE_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              env: $(ENV)
              # Common Configs
              wepayGrpcUrl: $(WEPAY_GRPC_URL)
              # Cancel Payment Retry Job
              paymentCancelRetryJobImageRepositoryName: $(PAYMENT_CANCEL_RETRY_JOB_IMAGE_REPOSITORY_NAME)
              paymentCancelRetryJobConfigMongoDbConnString: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_CONN_STRING)
              paymentCancelRetryJobConfigMongoDbDatabase: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_DATABASE)
              paymentCancelRetryJobConfigMongoDbCollectionName: $(PAYMENT_CANCEL_RETRY_JOB_MONGODB_COLLECTION_NAME)
              paymentCancelRetryJobConfigCronSchedule: $(PAYMENT_CANCEL_RETRY_JOB_CRON_SCHEDULE)
              paymentCancelRetryJobConfigSuccessfulJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_SUCCESSFUL_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobConfigFailedJobHistoryLimit: $(PAYMENT_CANCEL_RETRY_JOB_FAILED_JOB_HISTORY_LIMIT)
              paymentCancelRetryJobNodeSelectorPool: $(PAYMENT_CANCEL_RETRY_JOB_NODE_SELECTOR_POOL)                            