trigger: none

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: TST_Atg_Comm_Hub_Deploy
  displayName: TST - Atg Comm Hub Deploy

  jobs:
  - deployment: App_Service_Deploy
    displayName: App Service Deploy
    environment: atg-commhub-tst

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: atg-commhub-tst
    - name: latestTag
      value: ''

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../integration-svcs/app-svc-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              acrServerUrl: https://acreastusshrapteancr.azurecr.io
              acrUsername: acreastusshrapteancr
              acrPassword: $(ACR_PASSWORD_SHR)
              azureTenantId: '560ec2b0-df0c-4e8c-9848-a15718863bb6'
              appServiceName: 'apsvc-eastus-tst-integration-commhub'
              containerRegistryName: 'acreastusshrapteancr.azurecr.io'
              imageRepositoryName: 'integration-communication-hub'
              appInsightsInstrumentationKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              appInsightsConnString: $(APP_INSIGHTS_CONN_STRING)
              gqlUrlSubsMgmt: $(GQL_URL_SUBS_MGMT)
              sbConnString: $(SB_CONN_STRING)
              sbResultSubscriptionName: $(SB_RESULT_SUBSCRIPTION_NAME)
              sbSubscriptionName: $(SB_SUBSCRIPTION_NAME)
              sbTopicName: $(SB_TOPIC_NAME)
              signalRConnString: $(SIGNALR_CONN_STRING)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              subsMgmtTenantSecret: $(SUBS_MGMT_TENANT_SECRET)      

- stage: STG_Atg_Comm_Hub_Deploy
  displayName: STG - Atg Comm Hub Deploy
  dependsOn: TST_Atg_Comm_Hub_Deploy  

  jobs:
  - deployment: App_Service_Deploy
    displayName: App Service Deploy
    environment: atg-commhub-stg

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: atg-commhub-stg
    - name: latestTag
      value: ''

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../integration-svcs/app-svc-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              acrServerUrl: https://acreastusshrapteancr.azurecr.io
              acrUsername: acreastusshrapteancr
              acrPassword: $(ACR_PASSWORD_SHR)
              azureTenantId: '560ec2b0-df0c-4e8c-9848-a15718863bb6'
              appServiceName: 'apsvc-eastus-stg-integration-commhub'
              containerRegistryName: 'acreastusshrapteancr.azurecr.io'
              imageRepositoryName: 'integration-communication-hub'
              appInsightsInstrumentationKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              appInsightsConnString: $(APP_INSIGHTS_CONN_STRING)
              gqlUrlSubsMgmt: $(GQL_URL_SUBS_MGMT)
              sbConnString: $(SB_CONN_STRING)
              sbResultSubscriptionName: $(SB_RESULT_SUBSCRIPTION_NAME)
              sbSubscriptionName: $(SB_SUBSCRIPTION_NAME)
              sbTopicName: $(SB_TOPIC_NAME)
              signalRConnString: $(SIGNALR_CONN_STRING)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              subsMgmtTenantSecret: $(SUBS_MGMT_TENANT_SECRET)     

- stage: PRF_Atg_Comm_Hub_Deploy
  displayName: PRF - Atg Comm Hub Deploy
  dependsOn: TST_Atg_Comm_Hub_Deploy

  jobs:
  - deployment: App_Service_Deploy
    displayName: App Service Deploy
    environment: atg-commhub-prf

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: atg-commhub-prf
    - name: latestTag
      value: ''

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../integration-svcs/app-svc-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              acrServerUrl: https://acreastusshrapteancr.azurecr.io
              acrUsername: acreastusshrapteancr
              acrPassword: $(ACR_PASSWORD_SHR)
              azureTenantId: '560ec2b0-df0c-4e8c-9848-a15718863bb6'
              appServiceName: 'apsvc-eastus-prf-integration-commhub'
              containerRegistryName: 'acreastusshrapteancr.azurecr.io'
              imageRepositoryName: 'integration-communication-hub'
              appInsightsInstrumentationKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              appInsightsConnString: $(APP_INSIGHTS_CONN_STRING)
              gqlUrlSubsMgmt: $(GQL_URL_SUBS_MGMT)
              sbConnString: $(SB_CONN_STRING)
              sbResultSubscriptionName: $(SB_RESULT_SUBSCRIPTION_NAME)
              sbSubscriptionName: $(SB_SUBSCRIPTION_NAME)
              sbTopicName: $(SB_TOPIC_NAME)
              signalRConnString: $(SIGNALR_CONN_STRING)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              subsMgmtTenantSecret: $(SUBS_MGMT_TENANT_SECRET)   

- stage: PRD_Atg_Comm_Hub_Deploy
  displayName: PRD - Atg Comm Hub Deploy
  dependsOn: STG_Atg_Comm_Hub_Deploy  

  jobs:
  - deployment: App_Service_Deploy
    displayName: App Service Deploy
    environment: atg-commhub-prd

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: atg-commhub-prd
    - name: latestTag
      value: ''

    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../integration-svcs/app-svc-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-PRD'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_PRD)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_PRD)
              acrServerUrl: https://acreastusprdapteancr.azurecr.io
              acrUsername: acreastusprdapteancr
              acrPassword: $(ACR_PASSWORD_PRD)
              azureTenantId: '560ec2b0-df0c-4e8c-9848-a15718863bb6'
              appServiceName: 'apsvc-eastus-prd-integration-commhub'
              containerRegistryName: 'acreastusprdapteancr.azurecr.io'
              imageRepositoryName: 'integration-communication-hub'
              appInsightsInstrumentationKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              appInsightsConnString: $(APP_INSIGHTS_CONN_STRING)
              gqlUrlSubsMgmt: $(GQL_URL_SUBS_MGMT)
              sbConnString: $(SB_CONN_STRING)
              sbResultSubscriptionName: $(SB_RESULT_SUBSCRIPTION_NAME)
              sbSubscriptionName: $(SB_SUBSCRIPTION_NAME)
              sbTopicName: $(SB_TOPIC_NAME)
              signalRConnString: $(SIGNALR_CONN_STRING)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              subsMgmtTenantSecret: $(SUBS_MGMT_TENANT_SECRET)                   

                          