trigger: none

resources:
  pipelines:
  - pipeline: ezpay-email-notifications-docker-build-push
    source: ezpay-email-notifications-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config

stages:
- stage: DEV_Email_Notification_Svc_Helm_Deploy
  displayName: DEV - Ezpay Email Notifications SVC Helm Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-email-notification-svc-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              emailTemplateLogoUrl: $(EMAIL_TEMPLATE_LOGO_URL)
              platformEmail: $(PLATFORM_EMAIL)
              platformName: $(PLATFORM_NAME)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              merchantPortalUrl: $(MERCHANT_PORTAL_URL)
              payerPortalUrl: $(PAYER_PORTAL_URL)            
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)
              serviceBusConnectionString: $(SB_CONN_STRING)
              sbEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_DATABASE)
              cosmosContainer: $(COSMOSDB_DATA_PROJECTIONS_COLLECTION)                

- stage: TST_Email_Notification_Svc_Helm_Deploy
  displayName: TST - Ezpay Email Notifications SVC Helm Deploy
  dependsOn: DEV_Email_Notification_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-tst

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-email-notification-svc-tst
    - template: helm-variables-tst.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              emailTemplateLogoUrl: $(EMAIL_TEMPLATE_LOGO_URL)
              platformEmail: $(PLATFORM_EMAIL)
              platformName: $(PLATFORM_NAME)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              merchantPortalUrl: $(MERCHANT_PORTAL_URL)
              payerPortalUrl: $(PAYER_PORTAL_URL)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)
              serviceBusConnectionString: $(SB_CONN_STRING)
              sbEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_DATABASE)
              cosmosContainer: $(COSMOSDB_DATA_PROJECTIONS_COLLECTION)                

- stage: STG_Email_Notification_Svc_Helm_Deploy
  displayName: STG - Ezpay Email Notifications SVC Helm Deploy
  dependsOn: TST_Email_Notification_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-stg

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-email-notification-svc-stg
    - template: helm-variables-stg.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              emailTemplateLogoUrl: $(EMAIL_TEMPLATE_LOGO_URL)
              platformEmail: $(PLATFORM_EMAIL)
              platformName: $(PLATFORM_NAME)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              merchantPortalUrl: $(MERCHANT_PORTAL_URL)
              payerPortalUrl: $(PAYER_PORTAL_URL)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)
              serviceBusConnectionString: $(SB_CONN_STRING)
              sbEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_DATABASE)
              cosmosContainer: $(COSMOSDB_DATA_PROJECTIONS_COLLECTION)                        

- stage: PRD_Email_Notification_Svc_Helm_Deploy
  displayName: PRD - Ezpay Email Notifications SVC Helm Deploy
  dependsOn: STG_Email_Notification_Svc_Helm_Deploy

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: ezpay-prd

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: ezpay-email-notification-svc-prd
    - template: helm-variables-prd.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-PRD'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_PRD)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_PRD)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              replicas: $(REPLICAS)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              wepayGrpcUrl: $(GRPC_URL_WEPAY_INTEGRATION)
              broadcastPlatformEvents: $(BROADCAST_PLATFORM_EVENTS)
              emailTemplateLogoUrl: $(EMAIL_TEMPLATE_LOGO_URL)
              platformEmail: $(PLATFORM_EMAIL)
              platformName: $(PLATFORM_NAME)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              merchantPortalUrl: $(MERCHANT_PORTAL_URL)
              payerPortalUrl: $(PAYER_PORTAL_URL)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)
              serviceBusConnectionString: $(SB_CONN_STRING)
              sbEventsTopic: $(SB_PLATFORM_EVENTS_TOPIC)
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_DATABASE)
              cosmosContainer: $(COSMOSDB_DATA_PROJECTIONS_COLLECTION)                