pr: none
trigger: none

schedules:
# Run every day at 5 AM but only if code has changed.
- cron: "0 5 * * *"
  displayName: Integration Tests
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ezpay-integration-tests

resources:
  repositories:
  - repository: testing-e2e
    type: git
    name: testing-e2e 
    ref: CentralizeCypressCode   

stages:
  - stage: Ezpay_api_svc
    displayName: Run ezpay-api-svc test
    dependsOn: Init

    jobs:
    - template: ./templates/integration-test.yaml
      parameters:
        packageName: ezpay-api-svc

    - job: cleanUp
      steps:
      - task: replacetokens@3
        displayName: Replace tokens in cleanUp-config.json
        inputs:
          rootDirectory: $(System.DefaultWorkingDirectory)/devops-app-pipelines/src/pipelines/cypress-integration-test
          targetFiles: cleanUp-config.json
          encoding: auto
          writeBOM: true
          actionOnMissing: fail
          keepToken: false
          tokenPrefix: '#{'
          tokenSuffix: '}#'

      - script: |
          npm install crypto got
          node cleanUp.js      
        displayName: 'Clean up test data'
        workingDirectory: $(System.DefaultWorkingDirectory)/src        

  - stage: Payer_portal
    displayName: Run payer portal test
    dependsOn: Init 
    
    jobs:
    - template: ./templates/integration-test.yaml
      parameters:
        packageName: payer-portal

  - stage: Merchant_portal
    displayName: Run merchant portal test
    dependsOn: Init 

    jobs:
    - template: ./templates/integration-test.yaml
      parameters:
        packageName: merchant-portal

  #   jobs:
  #   - job: cleanUp
  #     steps:
  #     - task: replacetokens@3
  #       displayName: Replace tokens in cleanUp-config.json
  #       inputs:
  #         rootDirectory: $(System.DefaultWorkingDirectory)/devops-app-pipelines/src
  #         targetFiles: cleanUp-config.json
  #         encoding: auto
  #         writeBOM: true
  #         actionOnMissing: fail
  #         keepToken: false
  #         tokenPrefix: '#{'
  #         tokenSuffix: '}#'

  #     - script: |
  #         npm install crypto got
  #         node cleanUp.js      
  #       displayName: 'Clean up test data'
  #       workingDirectory: $(System.DefaultWorkingDirectory)/src
 
