trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: e2e-integration-tests

resources:
  repositories:
  - repository: testing-e2e
    type: git
    name: testing-e2e
    ref: refs/heads/master  

stages:
  - stage: eCommerce_sf
    displayName: Build and push eCommerce storefront cypress test docker image
    dependsOn: []

    jobs:
    - template: ./templates/docker-build-push.yaml
      parameters:
        packageName: ecomm-sf      
