trigger: none

resources:
  pipelines:
  - pipeline: subs-mgmt-api-svc-docker-build-push
    source: subs-mgmt-api-svc-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config
- group: new-relic-cli
- name: docker_image_tags
  value: ''

stages:
- stage: DEV_GQL_API_Svc_Helm_Deploy
  displayName: DEV - gql api-svc Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: subs-mgmt-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: subs-mgmt-api-svc-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)             
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)-gql
              chartName: $(CHART_NAME)
              env: $(ENV)
              location: $(LOCATION)
              replicas: $(REPLICAS)
              newRelicCliApiKey: $(NEW_RELIC_CLI_API_KEY)
              newRelicAccountId: $(NEW_RELIC_ACCOUNT_ID)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              b2cClientId: $(B2C_CLIENT_ID)
              b2cDomainHost: $(B2C_DOMAIN_HOST)
              b2cTenantId: $(B2C_TENANT_ID)
              b2cPolicyName: $(B2C_POLICY_NAME)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              serviceBusConnectionString: $(SB_CONN_STRING)
              sbEventsTopic: $(SB_EVENTS_TOPIC)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)         
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_SUBS_MGMT_DATABASE)
              cosmosContainer: $(COSMOSDB_SUBS_MGMT_CONTAINER)
              enableIntrospection: $(ENABLE_INTROSPECTION)
              enableTracing: $(ENABLE_TRACING)
              apiKind: GQL
              nodeSelectorPool: $(NODE_SELECTOR_POOL)
              eventsSbConnString: $(EVENTS_SB_CONN_STRING)
              eventsSbQueue: $(EVENTS_SB_QUEUE)

- stage: DEV_GRPC_API_Svc_Helm_Deploy
  displayName: DEV - grpc api-svc Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: subs-mgmt-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: subs-mgmt-api-svc-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)-grpc
              chartName: $(CHART_NAME)
              env: $(ENV)
              location: $(LOCATION)
              replicas: $(REPLICAS)
              newRelicCliApiKey: $(NEW_RELIC_CLI_API_KEY)
              newRelicAccountId: $(NEW_RELIC_ACCOUNT_ID)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              b2cClientId: $(B2C_CLIENT_ID)
              b2cDomainHost: $(B2C_DOMAIN_HOST)
              b2cTenantId: $(B2C_TENANT_ID)
              b2cPolicyName: $(B2C_POLICY_NAME)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              serviceBusConnectionString: $(SB_CONN_STRING)
              sbEventsTopic: $(SB_EVENTS_TOPIC)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)    
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_SUBS_MGMT_DATABASE)
              cosmosContainer: $(COSMOSDB_SUBS_MGMT_CONTAINER)                                                   
              apiKind: GRPC
              nodeSelectorPool: $(NODE_SELECTOR_POOL)
              eventsSbConnString: $(EVENTS_SB_CONN_STRING)
              eventsSbQueue: $(EVENTS_SB_QUEUE)              