trigger: none

resources:
  pipelines:
  - pipeline: comms-api-svc-docker-build-push
    source: comms-api-svc-docker-build-push
    trigger:
      branches:
        include:
        - master

variables:
- group: helm-chart-svc-principal-config
- group: new-relic-cli
- name: docker_image_tags
  value: ''
- template: ../../pipeline-base-variables.yaml@templates

stages:
- stage: DEV_Comms_Api_Svc_Helm_Deploy
  displayName: DEV (EAST) - Comms Api Svc Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: foundational-multi-cluster-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: comms-api-svc-dev
    - template: helm-variables-dev.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              location: $(LOCATION)
              releaseVersion: $(RELEASE_VERSION)
              replicas: $(REPLICAS)
              newRelicCliApiKey: $(NEW_RELIC_CLI_API_KEY)
              newRelicAccountId: $(NEW_RELIC_ACCOUNT_ID)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_COMMS_API_SVC_DATABASE)
              cosmosContainer: $(COSMOSDB_COMMS_API_SVC_CONTAINER)
              serviceBusConnectionString: $(SB_CONN_STRING)
              managementConnectionString: $(SB_MANAGEMENT_CONN_STRING)
              sbSmsReqQueue: $(SB_SMS_REQ_QUEUE)
              sbEmailReqQueue: $(SB_EMAIL_REQ_QUEUE)
              sbEventsTopic: $(SB_EVENTS_TOPIC)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)
              b2cClientId: $(B2C_CLIENT_ID)
              b2cDomainHost: $(B2C_DOMAIN_HOST)
              b2cTenantId: $(B2C_TENANT_ID)
              b2cPolicyName: $(B2C_POLICY_NAME)
              subsMgmtGrpcUrl: $(GRPC_URL_SUBS_MGMT)
              subsMgmtServiceId: $(SUBS_MGMT_SERVICE_ID)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              smsFromPhoneNumber: $(SMS_FROM_PHONE_NUMBER)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              batchSize: $(BATCH_SIZE)
              executionMode: $(EXECUTION_MODE)
              nodeSelectorPool: $(NODE_SELECTOR_POOL)

- stage: DEV_Comms_Api_Svc_Helm_Deploy_West
  displayName: DEV (WEST) - Comms Api Svc Helm Deploy
  dependsOn: []

  jobs:
  - deployment: Helm_Deploy
    displayName: Helm Deploy
    environment: foundational-multi-cluster-dev

    pool:
      vmImage: 'ubuntu-latest'

    variables:
    - group: comms-api-svc-dev-west
    - template: helm-variables-dev.yaml
    - template: ./region-overrides/helm-variables-dev-west.yaml

    strategy:
      runOnce:
        deploy:
          steps:
          - template: helm-deploy-step.yaml
            parameters:
              serviceConnection: 'AzDevOps-Pipeline-Principal-DEV-TST-STG'
              svcPrincipalClientId: $(SVC_PRINCIPAL_CLIENT_ID_SHR)
              svcPrincipalSecret: $(SVC_PRINCIPAL_SECRET_SHR)
              azureTenantId: $(AZURE_TENANT_ID)
              aksName: $(AKS_NAME)
              aksResourceGroup: $(AKS_RESOURCE_GROUP)
              containerRegistryName: $(CONTAINER_REGISTRY_NAME)
              imageRepositoryName: $(IMAGE_REPOSITORY_NAME)
              chartRepositoryName: $(CHART_REPOSITORY_NAME)
              k8sNamespace: $(K8S_NAMESPACE)
              helmReleaseName: $(HELM_RELEASE_NAME)
              chartName: $(CHART_NAME)
              env: $(ENV)
              location: $(LOCATION)
              releaseVersion: $(RELEASE_VERSION)
              replicas: $(REPLICAS)
              newRelicCliApiKey: $(NEW_RELIC_CLI_API_KEY)
              newRelicAccountId: $(NEW_RELIC_ACCOUNT_ID)
              frontDoorId: $(FRONT_DOOR_ID)
              kongIngressClass: $(KONG_INGRESS_CLASS)
              kongIngressUpstreamHostHeader: $(KONG_INGRESS_UPSTREAM_HEADER)
              resourceLimitsCpu: $(RESOURCE_LIMITS_CPU)
              resourceLimitsMemory: $(RESOURCE_LIMITS_MEMORY)
              resourceRequestsCpu: $(RESOURCE_REQUESTS_CPU)
              resourceRequestsMemory: $(RESOURCE_REQUESTS_MEMORY)
              appInsightsKey: $(APP_INSIGHTS_INSTRUMENTATION_KEY)
              cosmosConnString: $(COSMOSDB_CONN_STRING)
              cosmosDatabase: $(COSMOSDB_COMMS_API_SVC_DATABASE)
              cosmosContainer: $(COSMOSDB_COMMS_API_SVC_CONTAINER)
              serviceBusConnectionString: $(SB_CONN_STRING)
              managementConnectionString: $(SB_MANAGEMENT_CONN_STRING)
              sbSmsReqQueue: $(SB_SMS_REQ_QUEUE)
              sbEmailReqQueue: $(SB_EMAIL_REQ_QUEUE)
              sbEventsTopic: $(SB_EVENTS_TOPIC)
              sbPlatformEventsSubscription: $(SB_PLATFORM_EVENTS_SUBSCRIPTION)
              b2cClientId: $(B2C_CLIENT_ID)
              b2cDomainHost: $(B2C_DOMAIN_HOST)
              b2cTenantId: $(B2C_TENANT_ID)
              b2cPolicyName: $(B2C_POLICY_NAME)
              subsMgmtGrpcUrl: $(GRPC_URL_SUBS_MGMT)
              subsMgmtServiceId: $(SUBS_MGMT_SERVICE_ID)
              subsMgmtApiKey: $(SUBS_MGMT_API_KEY)
              smsFromPhoneNumber: $(SMS_FROM_PHONE_NUMBER)
              processPlatformEvents: $(PROCESS_PLATFORM_EVENTS)
              batchSize: $(BATCH_SIZE)
              executionMode: $(EXECUTION_MODE)
              nodeSelectorPool: $(NODE_SELECTOR_POOL)
